name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.4"
      - name: Run common tests
        run: lua test/test_common.lua
      - name: Run preedit tests
        run: lua test/test_preedit.lua
      - name: Run convert tests
        run: lua test/test_convert.lua
